name: .NET Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  patcher-tests:
    name: Run Liquip.Patcher.Tests

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Create local feed folder
        run: mkdir packages

      - name: Update NuGet.config
        run: |
          echo '<?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <packageSources>
              <add key="LocalSource" value="./packages" />
              <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
            </packageSources>
          </configuration>' > NuGet.config

      - name: Pack Analyzer
        run: dotnet pack ./Liquip.Patcher.Analzyer/Liquip.Patcher.Analzyer.Package/Liquip.Patcher.Analzyer.Package.csproj --configuration Debug -o ./packages

      - name: Restore Dependencies
        run: dotnet restore ./Liquip.Patcher.Tests/Liquip.Patcher.Tests.csproj --source ./packages --source https://api.nuget.org/v3/index.json

      - name: Build Liquip.Patcher.Tests
        run: dotnet build ./Liquip.Patcher.Tests/Liquip.Patcher.Tests.csproj --configuration Debug --no-restore

      - name: Run Tests
        run: dotnet test ./Liquip.Patcher.Tests/Liquip.Patcher.Tests.csproj --no-build --configuration Debug --logger "trx;LogFileName=Liquip.Patcher.Tests.trx"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Liquip.Patcher.Tests-Results
          path: ./Liquip.Patcher.Tests/TestResults/Liquip.Patcher.Tests.trx

  scanner-tests:
    name: Run Liquip.Scanner.Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore ./Liquip.Scanner.Tests/Liquip.Scanner.Tests.csproj

      - name: Build Liquip.Scanner.Tests
        run: dotnet build ./Liquip.Scanner.Tests/Liquip.Scanner.Tests.csproj --configuration Debug --no-restore

      - name: Run Tests
        run: dotnet test ./Liquip.Scanner.Tests/Liquip.Scanner.Tests.csproj --no-build --configuration Debug --logger "trx;LogFileName=Liquip.Scanner.Tests.trx"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Liquip.Scanner.Tests-Results
          path: ./Liquip.Scanner.Tests/TestResults/Liquip.Scanner.Tests.trx
