name: .NET Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  setup:
    name: Setup .NET and Restore Dependencies
    runs-on: windows-latest
    outputs:
      dotnet-version: ${{ steps.dotnet-setup.outputs.dotnet-version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        id: dotnet-setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Clean Solution
        run: dotnet clean nativeaot-patcher.sln

      - name: Restore Dependencies
        run: dotnet restore nativeaot-patcher.sln
  patcher-tests:
    name: Run Liquip.Patcher.Tests
    runs-on: windows-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ needs.setup.outputs.dotnet-version }}

      - name: Build Liquip.Patcher.Tests
        run: dotnet build ./tests/Liquip.Patcher.Tests/Liquip.Patcher.Tests.csproj --configuration Debug --no-restore

      - name: Run Tests
        run: dotnet test ./tests/Liquip.Patcher.Tests/Liquip.Patcher.Tests.csproj --no-build --configuration Debug --logger "trx;LogFileName=Liquip.Patcher.Tests.trx"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Liquip.Patcher.Tests-Results
          path: ./tests/Liquip.Patcher.Tests/TestResults/Liquip.Patcher.Tests.trx
  scanner-tests:
    name: Run Liquip.Scanner.Tests
    runs-on: windows-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ needs.setup.outputs.dotnet-version }}

      - name: Build Liquip.Scanner.Tests
        run: dotnet build ./tests/Liquip.Scanner.Tests/Liquip.Scanner.Tests.csproj --no-restore --configuration Debug 

      - name: Run Tests
        run: dotnet test ./tests/Liquip.Scanner.Tests/Liquip.Scanner.Tests.csproj --no-build --configuration Debug --logger "trx;LogFileName=Liquip.Scanner.Tests.trx"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Liquip.Scanner.Tests-Results
          path: ./tests/Liquip.Scanner.Tests/TestResults/Liquip.Scanner.Tests.trx
  analyzer-tests:
    name: Run Liquip.Patcher.Analyzer.Tests
    runs-on: windows-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ needs.setup.outputs.dotnet-version }}

      - name: Build Liquip.Patcher.Analyzer.Tests
        run: dotnet build ./tests/Liquip.Patcher.Analyzer.Tests/Liquip.Patcher.Analyzer.Tests.csproj --configuration Debug --no-restore

      - name: Run Tests
        run: dotnet test ./tests/Liquip.Patcher.Analyzer.Tests/Liquip.Patcher.Analyzer.Tests.csproj --no-build --configuration Debug --logger "trx;LogFileName=Liquip.Patcher.Analyzer.Tests.trx"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Liquip.Patcher.Analyzer.Tests-Results
          path: ./tests/Liquip.Patcher.Analyzer.Tests/TestResults/Liquip.Patcher.Analyzer.Tests.trx
